import 'data.dart';

loadContent(int chapterno) {
  switch (chapterno) {
    case 1:
      return ChapterData.ch1;
    case 2:
      return ChapterData.ch2;
    case 3:
      return ChapterData.ch3;
    case 4:
      return ChapterData.ch4;
    case 5:
      return ChapterData.ch5;
    case 6:
      return ChapterData.ch6;
    case 7:
      return ChapterData.ch7;
    case 8:
      return ChapterData.ch8;
    case 9:
      return ChapterData.ch9;
    case 10:
      return ChapterData.ch10;
    case 11:
      return ChapterData.ch11;
    case 12:
      return ChapterData.ch12;
    case 13:
      return ChapterData.ch13;
    case 14:
      return ChapterData.ch14;
    case 15:
      return ChapterData.ch15;
    case 16:
      return ChapterData.ch16;
    case 17:
      return ChapterData.ch17;
    case 18:
      return ChapterData.ch18;
    case 19:
      return ChapterData.ch19;
    case 20:
      return ChapterData.ch20;
    case 21:
      return ChapterData.ch21;
    case 22:
      return ChapterData.ch22;
    case 23:
      return ChapterData.ch23;
    case 24:
      return ChapterData.ch24;
    case 25:
      return ChapterData.ch25;
    case 26:
      return ChapterData.ch26;
    case 27:
      return ChapterData.ch27;
    case 28:
      return ChapterData.ch28;
    case 29:
      return ChapterData.ch29;
    case 30:
      return ChapterData.ch30;
    case 31:
      return ChapterData.ch31;
    case 32:
      return ChapterData.ch32;
    case 33:
      return ChapterData.ch33;
    case 34:
      return ChapterData.ch34;
    case 35:
      return ChapterData.ch35;
    case 36:
      return ChapterData.ch36;
    case 37:
      return ChapterData.ch37;
    case 38:
      return ChapterData.ch38;
    case 39:
      return ChapterData.ch39;
    case 40:
      return ChapterData.ch40;
  }
}
